# Generated by Django 2.2 on 2022-03-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('date', models.CharField(max_length=128, unique=True)),
                ('desc', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
